### ISSUE TITLE
4.20 MyArticyProject.build.cs Plugin Error

### ISSUE THREAD

**Issue by tobiaswarth** [ArticySoftware/ArticyImporterForUnreal#10]
Hi, just to let u know. I Updated from 4.18 to 4.20.2 and ran into Build Error. The line:

PublicIncludePaths.AddRange(new string[] { Path.Combine(ModuleDirectory, "../../Plugins/ArticyImporter/Source/ArticyRuntime/Public") });

is not working correctly for 4.20 it seems. In the readme u write that we have to go 2 folders up "../../" but we only need to go 1 up "../". Maybe correct that in the readme. 

Best regards
Tobi

**Comment by christian-schildt** [comment]
Hi Tobi,

Thanks for reporting this issue. On my machine (Windows 10, UE 4.20.2) I have the reversed case. Going two folders up works and going one folder up doesn’t.

When I put the line `Log.WriteLineOnce(LogEventType.Warning, LogFormatOptions.None, ModuleDirectory);` into my [ProjectName].Build.cs file it prints me something to the console that follows this structure: `[PathToProjectFolder]\Source\[ProjectName]`

This is how my folders are structured:

![2018-09-10 14_44_37-greenshot](https://user-images.githubusercontent.com/38693641/45298657-7c53cd00-b509-11e8-899b-e9ad5cc83268.png)

Which result do you get, when you print the module directory to the console and which operating system do you use?

Best regards,
Chris

**Comment by tobiaswarth** [comment]
Hey, i found out it's another problem... u can close this ticket i think.
I am using Engine Version 4.20.3 and the problem is that it throws me an error if i try to use "Path.combine".
The Engine tells me that "Path" is unknown. so nothing to do with ur plugin. I still did not find an answer to this, i just ignore the path.combine and add the path manually. this looks like follwing:

PublicIncludePaths.AddRange(new string[] {"../Plugins/ArticyImporter/Source/ArticyRuntime/Public"});

without the path.combine i need to go up one folder only.
