### ISSUE TITLE
Our studio has upgraded your plugin to Unreal Engine version 4.24. We would like to upload, but first discuss some very strange work-arounds we've had to make.

### ISSUE THREAD

**Issue by wvaughn409** [ArticySoftware/ArticyImporterForUnreal#23]
we don't want any compensation. Just want this plugin to stay current with Unreal. We had to add a large list of external dependencies to the Visual studio solution (manually adding each path one at a time), and we also have to fix this code every time we re-import and compile the project manually in VS:

`UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef CursorifConditionFalse */
class EMyProjectCursorifConditionFalse : uint8
{
	Value_00 = 0, //this was added to get the code to compile
	Value_01 = 1,
	Value_02 = 2,
	Value_03 = 3,
	Value_04 = 4,
	Value_05 = 5,
	Value_06 = 6,
	Value_07 = 7,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef CursorifConditionTrue */
class EMyProjectCursorifConditionTrue : uint8
{
	Value_00 = 0,  //this was added to get the code to compile
	Value_01 = 1,
	Value_02 = 2,
	Value_03 = 3,
	Value_04 = 4,
	Value_05 = 5,
	Value_06 = 6,
	Value_07 = 7,
};`

**Comment by Quexlaw** [comment]
Hello wvaughn and sorry for reaching out so late.

The plugin has officially been compatible with 4.24 for a while now, even before you opened this issue. The default behaviour for path includes changed in 4.24, but this has been accommodated for. Can you confirm the current release works as intended on your end?

Additionally, the enum bug has been resolved on articy draft's end. As UENUMs always have to have a zero value, it will notify you of missing zero values before you can export.

**Comment by Quexlaw** [comment]
As we haven't heard back from you in a while and reported issues are supposed to be fixed already. We'll close this issue.
