### ISSUE TITLE
UE 4.25

### ISSUE THREAD

**Issue by blackantmaster** [ArticySoftware/ArticyImporterForUnreal#26]
Hi,
I tryed to import and use the plugin with UE4.25, but it seems unable to update the builde compiling scripts.

**Comment by Quexlaw** [comment]
4.25 is not officially supported by us yet due to engine bugs that make hot reload very unreliable.

If you need it, there is a pull request #24 that you can adapt, but the issue in regards to hot reloading makes it hard(er) to work with than in 4.24

**Comment by Quexlaw** [comment]
Closed due to upcoming official 4.25 release.
