### ISSUE TITLE
How to read the content/field of an entity

### ISSUE THREAD

**Issue by ash501** [ArticySoftware/ArticyImporterForUnreal#3]
Hello,

I know this question may be early, but I think it's good to ask it anyway.

Assuming I created an entity with a custom template (using a custom field definition, so no standard template, but if needed I could use a standard one for the test) etc. in Articy to define the gameplay values. Let's say the entity has the two field "LP" and "Magic" with int values. 

I export the information to UE4 from Articy and import it in UE4.

I try getting the object with "GetArticyDB" and "GetObjectByName" via Blueprint.
How can I access the gameplay values defined for my entity?

Thanks and God bless you
Tobias

**Comment by nico-probst** [comment]
Hi Tobias,

After you have "get" the object you first need to cast it into the proper type. The type to cast in is the project name + Template name, so for example if your template is called `PlayerCharacter `(TechnicalName!) and your articy:draft project is called `MyRPG `then you are looking to cast into MyRPGPlayerCharacter. After that you need the name of the Feature inside your Template. For example lets say its called `Attributes`, then you will find a field called `Attribute `(Again TechnicalName). Inside attribute you will find all your properties (Also TechnicalNames). 
But i think its a very important question, so i will add some clarifications into the quick start guide to describe that process.
Thank you and let me know if that helped you or if you need any more information.

Best regards

Nico

**Comment by ash501** [comment]
Thanks Nico.
It worked fine. I'll continue to explore the plugin.

In general, I think it would be great if you can give us a roadmap of the features you're planning and when to have it. It would also help people to support you.

So long and God bless you

Tobias
