### ISSUE TITLE
Linker Error on GetInputPins Access

### ISSUE THREAD

**Issue by bmustiata** [ArticySoftware/ArticyImporterForUnreal#38]
I'm trying to create my own `ArticyFlowPlayer`. Unfortunately when trying to access input pins, while the compilation passes, the build fails with a linker error.

```
void UQuestFlowPlayer::Play(UObject* const Node)
{
	TQueue<UObject*> NodesToProcess;
	NodesToProcess.Enqueue(Node);

	while (!NodesToProcess.IsEmpty())
	{
		auto CurrentNode = *NodesToProcess.Peek();
		NodesToProcess.Pop();

		auto result = this->OnPlayerPaused.Execute(CurrentNode);

		// If the listener said the execution shouldn't continue, the execution shouldn't
		// continue.
		if (!result)
		{
			continue;
		}

		if (static_cast<UObjectBase*>(CurrentNode)->GetClass()->IsChildOf(UArticyFlowFragment::StaticClass()))
		{
			auto FlowFragment = static_cast<UArticyFlowFragment*>(CurrentNode);
			auto ArticyInputPins = FlowFragment->GetInputPins(); // <== linker fails if this line is not commented
```

From what I could tell it's caused by the fact the implementation is not exported as API, and is defined in the header. So adding just the `ARTICYRUNTIME_API` isn't enough. The PR is just extracting the code in it's own CPP, so it can be exposed as a normal API.

For some reason the output pins are in their own CPP file, so no change is needed there.

With this PR: https://github.com/ArticySoftware/ArticyImporterForUnreal/pull/37 it works fine.

**Comment by christian-schildt** [comment]
Thank you very much!
