### ISSUE TITLE
Works with 4.18

### ISSUE THREAD

**Issue by ash501** [ArticySoftware/ArticyImporterForUnreal#4]
Just to let you know...
I tried it yesterday with the **4.18** code and it compiles and seems to work. At least all my test are working just as fine as in 4.17.

Maybe in the next weeks, I'll run more tests and implementations.

So long and God bless you

**Comment by nico-probst** [comment]
Thank you very much for taking the time and testing this! Its very much appreciated.

Best regards

Nico
