### ISSUE TITLE
Inquiry about future releases of the plugin

### ISSUE THREAD

**Issue by wvaughn409** [ArticySoftware/ArticyImporterForUnreal#40]
Hi there. Is there a timeline for an upgraded version of the plugin that is compatible with Unreal Engine 5.0.0 Early Access 2 ?

**Comment by peter-sabath** [comment]
Our timeline to UE5 is to fix & change things that come up with UE 4.27 as the transitional version to UE 5.
UE5 has some differences regarding the UI customization which is currently investigated.
With the current holiday season, I can't give you a date, but we are working on it

**Comment by brwarner** [comment]
Hey @wvaughn409, we have a pre-release for Unreal 5 EA2. It hasn't been heavily tested yet so consider it a preview build for now.

https://github.com/ArticySoftware/ArticyImporterForUnreal/releases/tag/UE-5-pre1
