### ISSUE TITLE
Crash when executing Kismet Event Commands

### ISSUE THREAD

**Issue by DarioVangelista** [ArticySoftware/ArticyImporterForUnreal#68]
Hello,
we have encountered a crash on UE 4.27.1 when executing a Kismet Event Command.
We are using v1.3.1 of the importer.

It happens in both our project and the ManiacMansion demo.

Repro steps:
- press play in the editor
- open the console
- type 'ke* StatPerf' (but whatever command will trigger the crash)

From what I understand, the ArticyPackage needs to provide an implementation of UWorld* GetWorld() const;

This is blocking other people on the team from using Kismet Event Commands which is a problem.
I have avoided the crash locally by changing the implementation of UArticyBaseObject::GetWorld() to always return nullptr, but this is clearly not an actual fix and I have no idea how many things it might be breaking in Articy.

What should the actual implementation of UArticyPackage::GetWorld() be?

Thanks,
Dario @ YellowBrickGames

<img width="1897" alt="Articy_Crash" src="https://user-images.githubusercontent.com/93659169/145477219-72bb05e1-01c2-4645-9646-bf6627190d24.png">
.

**Comment by peter-sabath** [comment]
Hi Dario,

thanks for reporting this.

We think that the implementation in `UArticyPackage::GetWorld() ` should be 

```
UWorld* UArticyPackage::GetWorld() const
{
	return GetOuter() ? GetOuter()->GetWorld() : nullptr;
}
```

We will do some further checks for other unwanted side-effects but are confident that this would solve the problem.

**Comment by DarioVangelista** [comment]
Hi Peter,
I tried your change and unfortunately it doesnt change the result.

I have UArticyBaseObject::GetWorld() as in the original code:
UWorld* GetWorld() const override { return GEngine->GetWorldFromContextObjectChecked(GetOuter()); }

And UArticyPackage::GetWorld() as you proposed:
UWorld* GetWorld() const override { return GetOuter() ? GetOuter()->GetWorld() : nullptr;  }

Thanks,
Dario @ YellowBrickGames
<img width="1892" alt="Articy_Crash_2" src="https://user-images.githubusercontent.com/93659169/146551173-051eb518-5471-4878-93e6-54d1fb30207f.png">

**Comment by christian-schildt** [comment]
Hi Dario,

thanks for the further information.

As far as I can tell, your workaround to always return nullptr should be fine for now.

It seems like that overriding GetWorld() in our plugin is no longer needed. A few quick tests confirmed this. Probably, removing GetWorld() will be our solution. But won’t publish the change until the new year.
