### ISSUE TITLE
setProp with string properties fails to compile C++ in UE5.

### ISSUE THREAD

**Issue by apetribegames** [ArticySoftware/ArticyImporterForUnreal#69]
Using an Expresso instruction in Articy ( such as setProp(getObj("Quest1"), "Quest_Properties.Description", "hello") ) fails to compile C++ in UE5. I get a popup message within the UE5 editor saying:

"Aborting import process. No cache available to restore. Deleting import asset but leaving generated code intact. Please delete manually in Source/ArticyGenerated if necessary and rebuild. Reason: OtherCompilationError."

Using setProp for boolean or integer properties appears to work just fine.

**Comment by christian-schildt** [comment]
Hi,

Thanks for reporting this issue!
I was able to reproduce it and we will take a closer look at it soon.

Best regards,
Christian
