### ISSUE TITLE
Importing issues when renaming Templates/Features

### ISSUE THREAD

**Issue by nico-probst** [ArticySoftware/ArticyImporterForUnreal#7]
[Original post](https://www.nevigo.com/forum/viewtopic.php?f=48&t=18314#p21659) _thx dread for reporting it_

**Steps to reproduce**
1. Create new empty Unreal project
2. Install the Articy Importer plugin and enable it.
3. Export the fresh Maniac Manfred articy project to Unreal projects Content directory.
4. Import the generated articy project assets when prompted.
5. Go to articy project and change the Technical name of "Template Design/Templates/Entities/Character" to CharacterChanged.
6. Export the articy project.
7. Import the project in Unreal when prompted to.
8, Observer unreal engine crash.

**Workaround**
Deleting the whole Generated folder resolves the import

**Comment by Quexlaw** [comment]
This has been resolved a long time ago now, by deleting the old assets before creating new ones, which resolves an issue where Unreal tried overwriting an asset with the same path, but a different class.
